# don't build tags, it's redundant
if: tag IS blank
language: node_js
node_js:
  - 12
install: npm install
script:
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - export APPLITOOLS_CONCURRENCY=500
  - echo $APPLITOOLS_BATCH_ID
  - printenv
  - npm run build || travis_terminate 1;
  - npm run test || travis_terminate 1;
  - npm run release || travis_terminate 1;
  - npm run deploy || travis_terminate 1;
