# don't build tags, it's redundant
if: tag IS blank
language: node_js
node_js:
  - 12
branches:
  only:
    - /^release-.*$/
install: yarn install --frozen-lockfile
script:
  - npm run build || travis_terminate 1;
  - npm run release || travis_terminate 1;
