# don't build tags, it's redundant
if: tag IS blank
language: node_js
node_js:
  - 12
cache:
  npm: true
  directories:
    - ~/.cache
before_install:
  - npm i -g npm@latest
  - npm --version
install: npm install
script:
  - npm run build || travis_terminate 1;
  - npm run release || travis_terminate 1;
