name: bundleTests
on: [pull_request]

jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
      - run: npx midgard-yarn install --frozen-lockfile
      - run: npm run analyzeBundles --silent
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
