name: bundleTests
on: [pull_request]

jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run analyzeBundlesAndCompare --silent
      - name: updatePRComment
        if: always()
        run: npm run updatePRComment --prefix plugins-bundle-analyzer
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
