name: commitAfterMerge
on:
  pull_request:
    types: [closed]
# on:
#   push:
#     branches:
#       - master
jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run saveBundlesSizesBaseline
      - uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Updating the baseline bundlesSizes
          branch: githubActionOnMergePR
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
