# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler

# Ensures that only one task per branch will run at a time
concurrency:
  group: Labeler-${{ github.ref }}
  cancel-in-progress: true

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
