name: action
on: pull_request

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.0.0
        with:
          title-regex: '\w feat: \w|\w fix: \w|\w house: \w|\w breaking-change: \w'
          on-failed-regex-comment: 'Failed to match regex: `%regex%`!'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
