name: bundleTests
on: [pull_request]

jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run analyzeBundles --silent
        id: bundleSizesPRComment

  deploy_examples:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: deploy_PRComment
        id: deploy_PRComment
        run: npm run deployPRComment
      - run: echo "${{ steps.deploy_examples.outputs.deploy_message }}"

    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_comment_pr:
    name: update PR comment
    needs: [analyze-bundles, deploy_examples]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: updateComment
        run: npm run updatePRComment

    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      message: '${{ needs.analyze-bundles.steps.bundleSizesPRComment.outputs.bundleSizes_message }} ${{ needs.deploy_examples.steps.deploy_PRComment.outputs.deploy_message }}'
