name: bundleTests
on: [pull_request]

jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run analyzeBundles --silent
        id: bundleSizesPRComment
      - run: echo "${{ steps.bundleSizesPRComment.outputs.bundleSizes_message }}"

  update_comment_pr:
    name: update PR comment
    needs: [analyze-bundles]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: deploy_PRComment
        id: deploy_PRComment
        run: npm run deployPRComment
      - run: echo "${{ steps.deployPRComment.outputs.deploy_message }}"
      - name: updateComment
        run: npm run updatePRComment

    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      message: '${{ needs.analyze-bundles.steps.bundleSizesPRComment.outputs.bundleSizes_message }} \n'
