name: bundleTests
on: [pull_request]

env:
  SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run analyzeBundles --silent
        id: bundleSizesPRComment

  deploy_examples:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: deploy_PRComment
        id: deploy_PRComment
        run: npm run deployPRComment

  update_comment_pr:
    name: update PR comment
    needs: [analyze-bundles, deploy_examples]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run updatePRComment
        inputs:
          message: '${{ needs.analyze-bundles.steps.bundleSizesPRComment.outputs.bundleSizes_message }} ${{ needs.deploy_examples.steps.deploy_PRComment.outputs.deploy_message }}'
