name: prComment
on:
  pull_request:
    types: opened
jobs:
  examples-pr-comment:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: npm run deployPRComment
        id: deployPRComment
      # - uses: actions/checkout@v2
      # - run: npm install
      # - run: npm run deployPRComment
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: bundleTests
on: [pull_request]

jobs:
  analyze-bundles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install 
      - run: npm run analyzeBundles --silent
        id: bundleSizesPRComment
      # - uses: actions/checkout@v2
      # - run: npm install
      # - run: npm run analyzeBundles --silent
    # env:
    #   REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  comment_pr:
    name: update PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
      - uses: unsplash/comment-on-pr@master
      - run: npm run updatePRComment
        # uses: thollander/actions-comment-pull-request@master
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: '${{ analyze-bundles.steps.bundleSizesPRComment.outputs.bundleSizes_message }}\n ${{ examples-pr-comment.steps.deployPRComment.outputs.deploy_message }}'
