name: release
on:
  push:
    branches:
      - 'release*'
    tags:
      - v9.*
      - v8.*
      - v7.*
jobs:
  publishPackages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npx midgard-yarn install --frozen-lockfile
      - run: npm run build
      - run: npm run release
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL}}
