name: release
on:
  push:
    branches:
      - 'release*'
jobs:
  publishPackages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
      - run: npx midgard-yarn install --frozen-lockfile
      - run: npm run build
      - run: npm run release
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL}}
